server.port=8088
spring.application.name=customer-service
spring.datasource.url=jdbc:mysql://mysql:3306/customer_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=knoweb_admin_2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka/
eureka.instance.prefer-ip-address=true